# Generated by Django 4.1.4 on 2022-12-15 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_quizcontent_percentage_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='quiz_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.quizcontent'),
        ),
    ]
