# Generated by Django 4.1.4 on 2022-12-15 04:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_questionattempt_quiz_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizcontent',
            name='percentage_correct',
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
