# Generated by Django 4.1.4 on 2022-12-15 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_quizcontent_percentage_correct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionattempt',
            name='date_time',
        ),
    ]
