# Generated by Django 4.1.4 on 2022-12-19 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_questionattempt_submitted_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionattempt',
            name='correct',
        ),
    ]
